### ISSUE TITLE
Cannot invoke pbt as module

### ISSUE THREAD

**Issue by neontty** [SimpleDataLabsInc/prophecy-build-tool#121]
hi @pateash ,

https://github.com/SimpleDataLabsInc/prophecy-build-tool/blame/ee0369e22d409440cf950b05045c20bcddb82bcd/src/pbt/__init__.py#L405

We can no longer run pbt as a python module

```
$python -m pbt validate --path .
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3: No module named pbt.__main__; 'pbt' is a package and cannot be directly executed
```

This has broken setup at some customers which rely on calling as a module. If this change was necessary to enable private artifactory then I will find a workaround. Otherwise I want to revert

**Comment by pateash** [comment]
It was not working for private artifactory, I don't remember why,
Could you please check once

**Comment by neontty** [comment]
hi @pateash , how do I check for private artifactory? the unit tests for the private artifactory test are working after I slightly changed the import syntax to match other test files. 

all unit tests are passing.
